import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import Image from 'next/image'
import './globals.css'

const worksans = Work_Sans({ subsets: ['latin'], variable: '--font-work-sans' })
const wimp = localFont({
  src: './wimp.woff2',
  variable: '--font-wimp',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Deep Sea Betting',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${worksans.variable} ${wimp.variable}`}>
      <body>
        <Image
          fill
          quality={90}
          src="/assets/bg-desktop.png"
          alt="Deep sea betting logo"
          objectFit="cover"
          priority
        />
        {children}
      </body>
    </html>
  )
}
